FROM python:3.9
WORKDIR /app
COPY payment.ini .
COPY payment.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt
ENV CART_HOST = "cart" \
    CART_PORT = "8080" 
    USER_HOST = "user" \
    USER_PORT = "8080" \
    AMPQ_HOST = "rabbitmq" \
    AMPQ_USER = "roboshop" \
    AMPQ_PASS = "roboshop123"

    
CMD ["uwsgi", "--ini", "payment.ini"]