#builder stage

FROM python:3.9-slim as builder
WORKDIR /app

COPY requirements.txt .

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     gcc \
#     python3-dev \
#     && rm -rf /var/lib/apt/lists/* \
    

RUN pip3 install --no-cache-dir --prefix=/mypackages -r requirements.txt gcc python3-dev build-essential \
    && rm -rf /root/.cache/pip 
ENV PYTHONPATH=/mypackages/lib/python3.9/site-packages    

#production stage

FROM python:3.9-slim
WORKDIR /app
COPY --from=builder /mypackages /usr/lib


ENV CART_PORT=8080 \
    USER_HOST=user \
    USER_PORT=8080 \
    AMQP_HOST=rabbitmq \
    AMQP_USER=roboshop \
    AMQP_PASS=roboshop123

    
CMD ["uwsgi", "--ini", "payment.ini"]