
FROM node:20
WORKDIR /app
COPY package.json .
COPY *.js .
RUN npm install


FROM node:20-slim
WORKDIR /app
COPY --from=builder /app /app

# ENV MONGO = true \
#     REDIS = true \
#     MONGO_URL="mongodb://mongodb:27017/users" \
#     REDIS_URL="redis://redis:6379"
EXPOSE 27017
EXPOSE 6379
CMD ["node", "server.js"]
