services:
  catalouge:
    build:
      dockerfile: ./CATALOUGE.dockerfile
    image: catalouge:2.2.2
    container_name: catalouge
    depends_on:
    - mongodb
  mongodb:
    build:
      dockerfile: ./MONGODB.dockerfile
    image: mongodb:2.2.2
    container_name: mongodb  
networks:
  default: 
    driver: bridge
    name: roboshop
    external: true


    


  
  