services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: dockerfile
    image: frontend:2.2.2
    container_name: frontend
    ports:
      - "80:80"
     # - "443:443"
    depends_on:
      - catalouge
      - user
      - cart
      - shipping
      - payment

  payment:
    build:
      context: ./PAYMENT
      dockerfile: dockerfile
    image: payment:2.2.2
    container_name: payment
    depends_on:
      - rabitmq
      - cart
      - user
  cart:
    build:
      context: ./CART
      dockerfile: dockerfile
    image: cart:2.2.2
    container_name: cart
    depends_on:
      - redis
      - catalouge



  catalouge:
    build:
      context: ./CATALOUGE
      dockerfile: dockerfile
    image: catalogue:2.2.2
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build:
      context: ./ROBO-USER
      dockerfile: dockerfile
    image: user:2.2.2
    container_name: user
    depends_on: 
      - redis

  redis:
    build:
      context: ./REDIS
      dockerfile: dockerfile
    image: redis:2.2.2
    container_name: redis

  mysql:
    build:
      context: ./MYSQL
      dockerfile: dockerfile
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  

  shipping:
    build:
      context: ./SHIPPING
      dockerfile: dockerfile
    image: shipping:2.2.2
    container_name: shipping
    depends_on:
      - cart
      - mysql
  
  mongodb:
    build:
      context: ./MONGODB
      dockerfile: dockerfile
    image: mongodb:2.2.2
    container_name: mongodb  

  rabitmq:
    build:
      context: ./RABIT-MQ
      dockerfile: dockerfile
    image: rabbitmq:3.8.0
    container_name: rabitmq


networks:
  default: 
    driver: bridge
    name: roboshop
    external: true


    


  
  