FROM node:20 as builder

WORKDIR /app

COPY package.json .
COPY *.js .

RUN npm install


FROM node:20-slim
WORKDIR /app
COPY --from=builder /app /app

ENV REDIS_HOST="redis" \
    CATALOGUE_HOST="catalogue" \
    CATALOGUE_PORT="8080"
    

EXPOSE 8080

CMD ["node", "server.js"]


# FROM node:20
# # this creates /app and move there
# WORKDIR /app
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV REDIS_HOST="redis" \
#     CATALOGUE_HOST="catalogue" \
#     CATALOGUE_PORT="8080"
# CMD ["node", "server.js"]