# Use an official Maven image to build the application


FROM maven:3.9.14 as builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package  #mvn build the application and create the JAR file in the target directory  #clean package will clean the previous build and create a new JAR file in the 
 #RUN mv target/shipping-1.0.jar shipping.jar  # Rename the JAR file to a consistent name for the runtime stage


# Use an official OpenJDK image to run the application

FROM openjdk:latest
COPY --from=builder /app/target/shipping-1.0.jar shipping.jar
ENV CART_ENDPOINT="cart:8080" \
    DB_HOST="mysql" 
CMD ["java", "-jar", "shipping.jar"]
