FROM almalinux:9
RUN dnf install -y nginx -y
EXPOSE 80
ENV MONGO_USER = "roboshop" \
    MONGO_PASSWORD = "roboshop" \
    MONGO_URL = "mongodb://mongodb:27017/roboshop"
CMD ["nginx", "-g", "daemon off;"]  
LABEL maintainer="Sandeep"  \
        version="1.0"  \
        description="This is nginx image for roboshop project"  \
        company="SNDP"  \




        