# FROM node:20
# WORKDIR /app
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV MONGO = true \
#     MONGO_URL = "mongodb://mongodb:27017/catalogue"
# EXPOSE 27017
# CMD ["node", "server.js"]



# ---------- Stage 1: Build ----------
FROM node:20 AS builder

WORKDIR /app

COPY package.json ./
RUN npm install

COPY *.js ./

# ---------- Stage 2: Production ----------
FROM node:20-slim

WORKDIR /app

# Copy only necessary files from builder
COPY --from=builder /app /app

ENV MONGO=true \
    MONGO_URL="mongodb://mongodb:27017/catalogue"

EXPOSE 27017

CMD ["node", "server.js"]